### PR TITLE
Remove isomorphic fetch

### PR DESCRIPTION
**Pull request by choonkending**
Part of #705 

Unneeded dependency!

Aint nobody got time for an unneeded dep

### CODE REVIEW

**Comment by choonkending** [comment]
Self LGTM! Merging!

**Comment by lapinskicho** [comment]
Do we still need es6-promise?  Is it for providing polyfill for isomorphic-fetch its sole purpose being there? Or it has some other potential use?

**Comment by choonkending** [comment]
Good question @lapinskicho and having laser focus on minimizing dependencies! I'll have a look at lunch to see if `axios` needs a polyfill - otherwise we're removing it!!!

**Comment by choonkending** [comment]
Yep - axios expects the native es6 promise to be polyfilled - which makes sense. Read more [here](https://github.com/mzabriskie/axios#promises)

**Comment by lapinskicho** [comment]
Got it.  Thanks!

For minimizing dependencies, I found two more modules that may not be in (actual) use, namely "express-flash" and "method-override" - or please let me know if I missed something in the code that they are actually needed.

**Comment by lapinskicho** [comment]
Also now in the code, each of ./app/actions/users.js and ./app/actions/topics.js are calling polyfill() for axios, but ./app/services/topics.js is not calling polyfill() (a bug?) - seems like we should have a utility file that takes care of the polyfill-ed axios and export for all other modules to use?

**Comment by ZeroCho** [comment]
Method override is for future use of http PUT or DELETE request.
And I'm also wondering why polyfill() is needed because it can be put inside webpack.config.js

**Comment by lapinskicho** [comment]
My first thought was about server-side, so I checked Node 5 (this package requirement) support of Promise, and it doesn't support all of the es6 promise implementation.

http://node.green/#Promise

**Comment by choonkending** [comment]
>  each of ./app/actions/users.js and ./app/actions/topics.js are calling polyfill() for axios, but ./app/services/topics.js is not calling polyfill() (a bug?) - seems like we should have a utility file that takes care of the polyfill-ed axios and export for all other modules to use?

Yes you are right @lapinskicho ! Thanks for finding that. I think we should only need to call the polyfill once to be honest, possibly in the main file. 

@ZeroCho Do you have a webpack plugin for a polyfill? 

I'm creating an issue for this haha - so we can continue our conversation over there peeps!

**Pull request merged**
