### PR TITLE
Trying to replace the old HMR... (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by Cleanshooter**
So this PR is going to be kinda big and I'm going to need some help.  Right now this is not working so please do not accept it.  

Basically I'm trying to replace react-transform-hmr & babel-preset-react-hmre since both have been either abandoned or superseded.  

As I've gone down this path I'm getting stuck with some tough things to figure out.  In my current code base she can start up but once you change a file and Webpack HMR triggers you get this 

Errors:
```
combineReducers.js:122 Uncaught (in promise) TypeError: Cannot read property 'isFetching' of null
    at combination (combineReducers.js:122)
    at computeNextEntry (<anonymous>:2:27469)
    at recomputeStates (<anonymous>:2:27769)
    at <anonymous>:2:31382
    at dispatch (createStore.js:171)
    at createStore (createStore.js:245)
    at <anonymous>:3:4545
    at <anonymous>:3:985
    at <anonymous>:2:838
    at eval (applyMiddleware.js:30)
combination @ combineReducers.js:122
computeNextEntry @ VM29593:2
recomputeStates @ VM29593:2
(anonymous) @ VM29593:2
dispatch @ createStore.js:171
createStore @ createStore.js:245
(anonymous) @ VM29593:3
(anonymous) @ VM29593:3
(anonymous) @ VM29593:2
(anonymous) @ applyMiddleware.js:30
createStore @ createStore.js:57
configureStore @ configureStore.js:33
render @ app.jsx:50
render @ createPrototypeProxy.js:44
(anonymous) @ ReactCompositeComponent.js:796
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:795
_renderValidatedComponent @ ReactCompositeComponent.js:822
_updateRenderedComponent @ ReactCompositeComponent.js:746
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
performUpdateIfNecessary @ ReactCompositeComponent.js:559
performUpdateIfNecessary @ ReactReconciler.js:157
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueElementInternal @ ReactUpdateQueue.js:226
(anonymous) @ ReactMount.js:288
scrollMonitor @ ReactMount.js:276
_updateRootComponent @ ReactMount.js:287
_renderSubtreeIntoContainer @ ReactMount.js:374
render @ ReactMount.js:422
(anonymous) @ client.jsx:57
(anonymous) @ client.jsx:80
hotApply @ app.js:565
cb @ process-update.js:52
(anonymous) @ process-update.js:68

warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) -text: 123 -->Detail<!-- /react-text -->
 (server) -text: 123 -->Details<!-- /react-text --
printWarning @ warning.js:36
warning @ warning.js:60
_mountImageIntoNode @ ReactMount.js:507
mountComponentIntoNode @ ReactMount.js:112
perform @ Transaction.js:140
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ client.jsx:29
(anonymous) @ app.js:5862
__webpack_require__ @ app.js:658
fn @ app.js:86
(anonymous) @ client:3
(anonymous) @ app.js:9901
__webpack_require__ @ app.js:658
(anonymous) @ app.js:707
(anonymous) @ app.js:710

client.js:67 [HMR] connected
```

From what I can gather the HMR is losing track of the redux store on reload when the webpack HMR fires off.  This didn't happen when the old plugins were in place.  I think it has something to do with the way that hot-module-loader 3 (HML3) expects to work with react.

My next thing to try is to react factor the client so it is back to a single file (get rid of app) and try to upgrade to React Router Redux 4 (RRR4)... this will break some thing down stream possibly (because it has some pretty big changes but I think that it will play better the HML3.  Not sure yet...

Any insight from the community would be great!

-Joe

### CODE REVIEW

**Comment by slavab89** [comment]
I didnt dig into this (might have some time during the weekend) but see this [comment](https://github.com/gaearon/react-hot-boilerplate/pull/61#issuecomment-292741259). Maybe you also need to change the `publicPath` as well.

**Comment by slavab89** [comment]
Got stuck in the exact same place (reproduced on my own project) \= after some HMR trigger that causes a full page refresh, it fails to read the state =[
I dont know if its related to RR4 or not because it does say something in the docs that it will be better with RR4.
I've tried to set up RR4 according to [here](https://blog.emilecantin.com/web/react/javascript/2017/05/16/ssr-react-router-4-webpack-code-split.html) but i'm not if that is really the way + it was way to difficult for me 😢

**Comment by Cleanshooter** [comment]
@slavab89 you and me both... couldn't dedicate too much time to it either... to many other iron in the fire right now.... good to know I'm not the only one though ;)

**Comment by ZeroCho** [comment]
@Cleanshooter #919

**Pull request closed without merging**
