### PR TITLE
data encryption

### PR DESCRIPTION
**Pull request by ZeroCho**
#418

And I think we need to make **app/config** folder for configuration on client side
@jrodl3r @choonkending @caranicas @psimyn

### CODE REVIEW

**Comment by choonkending** [comment]
Awesome!

Yep I've also been thinking of a client side config.

I have 2 branches I want merged first :
- meta tag refactor (with react - helmet)
- fetch data on route change 

Both of these branches make significant folder changes so I don't want to step on anyone's changes. 

I wonder whether this as a performance impact.

**Comment by ZeroCho** [comment]
@choonkending Okay. I'll wait until you merge those two branches and change my codes after it

**Comment by jrodl3r** [comment]
I'll start testing this on my end

**Comment by jrodl3r** [comment]
@ZeroCho This works like a charm so far on latest build - Nice job man! that technique you used to encrypt/decrypt was clutch as well 👍

**Comment by jrodl3r** [comment]
just noticed error on `test` after adding encryption to GET + reducers:

```
ERROR in ./app/images/favicon.png
Module parse failed: /Users/xxx/app/images/favicon.png Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:0)
```

**Comment by jrodl3r** [comment]
@ZeroCho what about just adding a Heroku config-var and doing this (instead of modifying `helmconfig.js`)?

```javascript
const encryptKey = process.env.ENCRYPT_KEY || 'XYZ789';
```

I suppose you could stuff that into the helmconfig, or another config file - did you mention that?

**Comment by ZeroCho** [comment]
@jrodl3r I also think that putting encrypt_key in helmconfig.js is not appropriate. So I think it will be good if there is a separate config file.
And about the error, I'll test it. Anyway, I have to change this PR because this has conflicts.

**Comment by jrodl3r** [comment]
@ZeroCho should we also have an enabled/disabled FLAG in the config to allow for easy on/off _[off by default]_ control of encryption?

**Comment by ZeroCho** [comment]
@jrodl3r made appConfig files and modularized crypto-js to decrease size. Could you please review it?

**Comment by jrodl3r** [comment]
Looks good, will verify ASAP ; )

**Comment by jrodl3r** [comment]
also wondering if we can use:
`webpack.DefinePlugin({ __CRYPT_KEY__: process.env.CRYPT_KEY })`

to store the key as a Heroku config-var... and then inside appConfig:
`export const encryptKey = __CRYPT_KEY__ || 'ReactGo';`

**Comment by jrodl3r** [comment]
getting `SyntaxError: Unexpected token export` on `appConfig.js` for PROD Server

**Comment by ZeroCho** [comment]
@jrodl3r `SyntaxError: Unexpected token export` might not be this PR's problem. It's webpack's problem I guess.

`webpack.DefinePlugin({ __CRYPT_KEY__: process.env.CRYPT_KEY })`
I think it's a good idea.

**Comment by jrodl3r** [comment]
Ok. the problem I was having in `server.jsx` was because I was missing the quote tick marks on the send(`...`), so using this:
```javascript
const stateData = encryption
  ? "'" + AES.encrypt(JSON.stringify(initialState), encryptKey).toString() + "'"
  : JSON.stringify(initialState);
```
and then removing the single quotes here:
```javascript
...<script>window.__INITIAL_STATE__ = ${stateData};</script>...
```

**Comment by ZeroCho** [comment]
@choonkending I think this should be prioritized due to XSS possibility
[Link](https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0#.k39qmqizd)

**Comment by choonkending** [comment]
@ZeroCho Most definitely! Good point ! Added to the project wall!

**Pull request closed without merging**
