### PR TITLE
Code split

### PR DESCRIPTION
**Pull request by GGAlanSmithee**
Enables code splitting by using dynamic entry points in `routes.jsx`

high level features:

* enables code splitting on client
    - hashed chunks in prod mode (for caching and cache-busting)
    - named (id) in dev mode
* disables code splitting on server
* uses a webpack manifest file to make sure vendor chunks does not change unless code changes
* adds a vendor chunk as an example (the actual content of this can easily be changed though)

Please ask any questions regarding the implementation you might have.

### CODE REVIEW

**Comment by GGAlanSmithee** [comment]
This is a less opiniated alternative to https://github.com/reactGo/reactGo/pull/823 (even though dll bundles and code splitting is not mutually exclusive).

To see it in action, navigate the application while viewing only JS requests in the Chrome network tab.

**Comment by choonkending** [comment]
@GGAlanSmithee Thanks for this! Nice and clean. 

I am still on holiday atm, but very happy to see this PR! 

I am also attempting to improve our test setup slightly, so I will move to this after I am done with that!

**Comment by GGAlanSmithee** [comment]
@choonkending :+1: 

A few notes:

* The manifest is not strictly needed
    - Removing this would make this PR quite a bit smaller (much less changes to render middleware), but I would recommend keeping it, as it would othervise inline the webpack manifest in the last chunk (vendor) making it generate a new hash everytime a chunk is added / removed / changed.
* The server-side code-split prevention is not strictly needed
    - But it makes no sense to codesplit on the server

> I am also attempting to improve our test setup slightly,

Interesting :) I find the test framework provided in this boilerplate to be :100: (although I'm not testing UI related functionality too much)

**Comment by choonkending** [comment]
@GGAlanSmithee Have a look at #847 ! :D

**Comment by ZeroCho** [comment]
@GGAlanSmithee Have you ever used react-router@4? Currently, I cannot find any good way to split codes like v3.

**Comment by GGAlanSmithee** [comment]
@ZeroCho I made a comment regarding this in https://github.com/reactGo/reactGo/issues/827#issuecomment-278890438 

The only way that I know of is to use https://github.com/ctrlplusb/react-async-component or create your own similar functionality. I cannot vouch for  this though, as I am yet to transfer any of my projects to rr4 for this very reason (lack of "easy" code split integration)

**Comment by GGAlanSmithee** [comment]
@choonkending nice, that's a lot less boilerplate :)

**Comment by ZeroCho** [comment]
@GGAlanSmithee Thank you! I didn't transfer to rr4 for the same reason. I'm sad there's no clear and easy way to spit codes... I'll try your suggestion `react-async-component`

**Comment by slavab89** [comment]
I believe you've already seen this but just want to make a note about this
[react-router code-splitting](https://reacttraining.com/react-router/web/guides/code-splitting). On the bottom they say that they didnt really go in the way of SSR + code splitting because it seems too difficult..?

**Comment by ZeroCho** [comment]
@slavab89 I saw it too. It is too complicated to achieve both. I'm waiting for the successful reference to come out.

**Comment by GGAlanSmithee** [comment]
I can confirm that I am still blocked by no ssr + code split for rr4. I am seriously thinking of dropping ssr in my apps, atleast for the ones which are mostly protected behind auth.

**Comment by slavab89** [comment]
Cruising google a little and i actually found a few promising looking articles / repos
Also contains a github at the end https://blog.emilecantin.com/web/react/javascript/2017/05/16/ssr-react-router-4-webpack-code-split.html
A little old but explained pretty well https://medium.com/@apostolos/server-side-rendering-code-splitting-and-hot-reloading-with-react-router-v4-87239cfc172c
Its in TS but still readable https://github.com/luke-john/rr4-ssr-cs

Let me know what you think 😄

**Pull request closed without merging**
